### ISSUE TITLE
How to save SSH identity key in LastPass

### ISSUE THREAD

**Issue by hkusulja** [sjlouder/Lastpass-PS#64]
Can you please write example, on how to properly save and retrieve SSH identity key from/to LastPass and file in ~/.ssh/ folder

**Comment by sjlouder** [comment]
Currently saving items isn't supported/reliable, so that will need to be done outside of this module.

Depending on how you save it, there are a couple different ways to retrieve the information:

- Save the content of the file as a Note

```
	$Note = Get-Note 'SSH Key'
	$Note.Notes | Out-File ~/.ssh/id_rsa
```


- Save the file as a note attachment

```
	$Note = Get-Note 'SSH Key'
	$Note.Attachments | Where FileName -eq 'id_rsa' | Get-Attachment -FilePath ~/.ssh/id_rsa
```

- Save as a specialized SSH key note type

```
	$Note = Get-Note 'SSH Key'
	$Note.Notes.Private_Key | Out-File ~/.ssh/id_rsa
```

I would definitely recommend having a backup of any files you plan to overwrite, and to test that the file encoding and content is correct.

**Comment by sw25481** [comment]
This all works great except this 

	$Note = Get-Note 'SSH Key'
	$Note.Notes.Private_Key | Out-File ~/.ssh/id_rsa

This works 

echo $Note.Notes.'Private Key'
